steps:
- name: 'gcr.io/cloud-builders/docker'
args: ['build', '-t', 'us-west1-docker.pkg.dev/qwiklabs-gcp-02-b4f267a2ef89/my-repository/hello-app:v1.0', '.']
- name: 'gcr.io/cloud-builders/docker'
args: ['push', 'us-west1-docker.pkg.dev/qwiklabs-gcp-02-b4f267a2ef89/my-repository/hello-app:v1.0']
- name: 'gcr.io/cloud-builders/kubectl'
args: ['apply', '-f', 'prod/']
env:
- 'CLOUDSDK_COMPUTE_ZONE=us-west1-c'
- 'CLOUDSDK_CONTAINER_CLUSTER=hello-cluster'
